export const llms = [
  {
    organization: "01.AI",
    name: "01-ai Yi Chat (34B)",
    id: "zero-one-ai/Yi-34B-Chat",
    contextLength: 4096,
    parameterSize: 34, // Always in Billion
  },
  {
    organization: "Allen AI",
    name: "OLMo Instruct (7B)",
    id: "allenai/OLMo-7B-Instruct",
    contextLength: 2048,
    parameterSize: 7,
  },
  {
    organization: "Allen AI",
    name: "OLMo Twin-2T (7B)",
    id: "allenai/OLMo-7B-Twin-2T",
    contextLength: 2048,
    parameterSize: 7,
  },
  {
    organization: "Allen AI",
    name: "OLMo (7B)",
    id: "allenai/OLMo-7B",
    contextLength: 2048,
    parameterSize: 7,
  },
  {
    organization: "Austism",
    name: "Chronos Hermes (13B)",
    id: "Austism/chronos-hermes-13b",
    contextLength: 2048,
    parameterSize: 13,
  },
  {
    organization: "cognitivecomputations",
    name: "Dolphin 2.5 Mixtral 8x7b",
    id: "cognitivecomputations/dolphin-2.5-mixtral-8x7b",
    contextLength: 32768,
    parameterSize: 56,
  },
  {
    organization: "databricks",
    name: "DBRX Instruct",
    id: "databricks/dbrx-instruct",
    contextLength: 32768,
    parameterSize: 7,
  },
  {
    organization: "DeepSeek",
    name: "Deepseek Coder Instruct (33B)",
    id: "deepseek-ai/deepseek-coder-33b-instruct",
    contextLength: 16384,
    parameterSize: 33,
  },
  {
    organization: "DeepSeek",
    name: "DeepSeek LLM Chat (67B)",
    id: "deepseek-ai/deepseek-llm-67b-chat",
    contextLength: 4096,
    parameterSize: 67,
  },
  {
    organization: "garage-bAInd",
    name: "Platypus2 Instruct (70B)",
    id: "garage-bAInd/Platypus2-70B-instruct",
    contextLength: 4096,
    parameterSize: 70,
  },
  {
    organization: "Google",
    name: "Gemma Instruct (2B)",
    id: "google/gemma-2b-it",
    contextLength: 8192,
    parameterSize: 2,
  },
  {
    organization: "Google",
    name: "Gemma Instruct (7B)",
    id: "google/gemma-7b-it",
    contextLength: 8192,
    parameterSize: 7,
  },
  {
    organization: "Gryphe",
    name: "MythoMax-L2 (13B)",
    id: "Gryphe/MythoMax-L2-13b",
    contextLength: 4096,
    parameterSize: 13,
  },
  {
    organization: "LM Sys",
    name: "Vicuna v1.5 (13B)",
    id: "lmsys/vicuna-13b-v1.5",
    contextLength: 4096,
    parameterSize: 13,
  },
  {
    organization: "LM Sys",
    name: "Vicuna v1.5 (7B)",
    id: "lmsys/vicuna-7b-v1.5",
    contextLength: 4096,
    parameterSize: 7,
  },
  {
    organization: "Meta",
    name: "Code Llama Instruct (13B)",
    id: "codellama/CodeLlama-13b-Instruct-hf",
    contextLength: 16384,
    parameterSize: 13,
  },
  {
    organization: "Meta",
    name: "Code Llama Instruct (34B)",
    id: "codellama/CodeLlama-34b-Instruct-hf",
    contextLength: 16384,
    parameterSize: 34,
  },
  {
    organization: "Meta",
    name: "Code Llama Instruct (70B)",
    id: "codellama/CodeLlama-70b-Instruct-hf",
    contextLength: 4096,
    parameterSize: 70,
  },
  {
    organization: "Meta",
    name: "Code Llama Instruct (7B)",
    id: "codellama/CodeLlama-7b-Instruct-hf",
    contextLength: 16384,
    parameterSize: 7,
  },
  {
    organization: "Meta",
    name: "LLaMA-2 Chat (70B)",
    id: "meta-llama/Llama-2-70b-chat-hf",
    contextLength: 4096,
    parameterSize: 70,
  },
  {
    organization: "Meta",
    name: "LLaMA-2 Chat (13B)",
    id: "meta-llama/Llama-2-13b-chat-hf",
    contextLength: 4096,
    parameterSize: 13,
  },
  {
    organization: "Meta",
    name: "LLaMA-2 Chat (7B)",
    id: "meta-llama/Llama-2-7b-chat-hf",
    contextLength: 4096,
    parameterSize: 7,
  },
  {
    organization: "Meta",
    name: "LLaMA-3 Chat (8B)",
    id: "meta-llama/Llama-3-8b-chat-hf",
    contextLength: 8192,
    parameterSize: 8,
  },
  {
    organization: "Meta",
    name: "LLaMA-3 Chat (70B)",
    id: "meta-llama/Llama-3-70b-chat-hf",
    contextLength: 8192,
    parameterSize: 70,
  },
  {
    organization: "mistralai",
    name: "Mistral (7B) Instruct",
    id: "mistralai/Mistral-7B-Instruct-v0.1",
    contextLength: 8192,
    parameterSize: 7,
  },
  {
    organization: "mistralai",
    name: "Mistral (7B) Instruct v0.2",
    id: "mistralai/Mistral-7B-Instruct-v0.2",
    contextLength: 32768,
    parameterSize: 7,
  },
  {
    organization: "mistralai",
    name: "Mistral (7B) Instruct v0.3",
    id: "mistralai/Mistral-7B-Instruct-v0.3",
    contextLength: 32768,
    parameterSize: 7,
  },
  {
    organization: "mistralai",
    name: "Mixtral-8x7B Instruct (46.7B)",
    id: "mistralai/Mixtral-8x7B-Instruct-v0.1",
    contextLength: 32768,
    parameterSize: 46.7,
  },
  {
    organization: "mistralai",
    name: "Mixtral-8x22B Instruct (141B)",
    id: "mistralai/Mixtral-8x22B-Instruct-v0.1",
    contextLength: 65536,
    parameterSize: 141,
  },
  {
    organization: "NousResearch",
    name: "Nous Capybara v1.9 (7B)",
    id: "NousResearch/Nous-Capybara-7B-V1p9",
    contextLength: 8192,
    parameterSize: 7,
  },
  {
    organization: "NousResearch",
    name: "Nous Hermes 2 - Mistral DPO (7B)",
    id: "NousResearch/Nous-Hermes-2-Mistral-7B-DPO",
    contextLength: 32768,
    parameterSize: 7,
  },
  {
    organization: "NousResearch",
    name: "Nous Hermes 2 - Mixtral 8x7B-DPO (46.7B)",
    id: "NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO",
    contextLength: 32768,
    parameterSize: 46.7,
  },
  {
    organization: "NousResearch",
    name: "Nous Hermes 2 - Mixtral 8x7B-SFT (46.7B)",
    id: "NousResearch/Nous-Hermes-2-Mixtral-8x7B-SFT",
    contextLength: 32768,
    parameterSize: 46.7,
  },
  {
    organization: "NousResearch",
    name: "Nous Hermes LLaMA-2 (7B)",
    id: "NousResearch/Nous-Hermes-llama-2-7b",
    contextLength: 4096,
    parameterSize: 7,
  },
  {
    organization: "NousResearch",
    name: "Nous Hermes Llama-2 (13B)",
    id: "NousResearch/Nous-Hermes-Llama2-13b",
    contextLength: 4096,
    parameterSize: 13,
  },
  {
    organization: "NousResearch",
    name: "Nous Hermes-2 Yi (34B)",
    id: "NousResearch/Nous-Hermes-2-Yi-34B",
    contextLength: 4096,
    parameterSize: 34,
  },
  {
    organization: "OpenChat",
    name: "OpenChat 3.5 (7B)",
    id: "openchat/openchat-3.5-1210",
    contextLength: 8192,
    parameterSize: 7,
  },
  {
    organization: "OpenOrca",
    name: "OpenOrca Mistral (7B) 8K",
    id: "Open-Orca/Mistral-7B-OpenOrca",
    contextLength: 8192,
    parameterSize: 7,
  },
  {
    organization: "Qwen",
    name: "Qwen 1.5 Chat (0.5B)",
    id: "Qwen/Qwen1.5-0.5B-Chat",
    contextLength: 32768,
    parameterSize: 0.5,
  },
  {
    organization: "Qwen",
    name: "Qwen 1.5 Chat (1.8B)",
    id: "Qwen/Qwen1.5-1.8B-Chat",
    contextLength: 32768,
    parameterSize: 1.8,
  },
  {
    organization: "Qwen",
    name: "Qwen 1.5 Chat (4B)",
    id: "Qwen/Qwen1.5-4B-Chat",
    contextLength: 32768,
  },
  {
    organization: "Qwen",
    name: "Qwen 1.5 Chat (7B)",
    id: "Qwen/Qwen1.5-7B-Chat",
    contextLength: 32768,
    parameterSize: 7,
  },
  {
    organization: "Qwen",
    name: "Qwen 1.5 Chat (14B)",
    id: "Qwen/Qwen1.5-14B-Chat",
    contextLength: 32768,
    parameterSize: 14,
  },
  {
    organization: "Qwen",
    name: "Qwen 1.5 Chat (32B)",
    id: "Qwen/Qwen1.5-32B-Chat",
    contextLength: 32768,
    parameterSize: 32,
  },
  {
    organization: "Qwen",
    name: "Qwen 1.5 Chat (72B)",
    id: "Qwen/Qwen1.5-72B-Chat",
    contextLength: 32768,
    parameterSize: 72,
  },
  {
    organization: "Qwen",
    name: "Qwen 1.5 Chat (110B)",
    id: "Qwen/Qwen1.5-110B-Chat",
    contextLength: 32768,
    parameterSize: 110,
  },
  {
    organization: "Snorkel AI",
    name: "Snorkel Mistral PairRM DPO (7B)",
    id: "snorkelai/Snorkel-Mistral-PairRM-DPO",
    contextLength: 32768,
    parameterSize: 7,
  },
  {
    organization: "Snowflake",
    name: "Snowflake Arctic Instruct",
    id: "Snowflake/snowflake-arctic-instruct",
    contextLength: 4096,
    parameterSize: 7,
  },
  {
    organization: "Stanford",
    name: "Alpaca (7B)",
    id: "togethercomputer/alpaca-7b",
    contextLength: 2048,
    parameterSize: 7,
  },
  {
    organization: "Teknium",
    name: "OpenHermes-2-Mistral (7B)",
    id: "teknium/OpenHermes-2-Mistral-7B",
    contextLength: 8192,
    parameterSize: 7,
  },
  {
    organization: "Teknium",
    name: "OpenHermes-2.5-Mistral (7B)",
    id: "teknium/OpenHermes-2p5-Mistral-7B",
    contextLength: 8192,
    parameterSize: 7,
  },
  {
    organization: "Together",
    name: "LLaMA-2-7B-32K-Instruct (7B)",
    id: "togethercomputer/Llama-2-7B-32K-Instruct",
    contextLength: 32768,
    parameterSize: 7,
  },
  {
    organization: "Together",
    name: "RedPajama-INCITE Chat (3B)",
    id: "togethercomputer/RedPajama-INCITE-Chat-3B-v1",
    contextLength: 2048,
    parameterSize: 3,
  },
  {
    organization: "Together",
    name: "RedPajama-INCITE Chat (7B)",
    id: "togethercomputer/RedPajama-INCITE-7B-Chat",
    contextLength: 2048,
    parameterSize: 7,
  },
  {
    organization: "Together",
    name: "StripedHyena Nous (7B)",
    id: "togethercomputer/StripedHyena-Nous-7B",
    contextLength: 32768,
    parameterSize: 7,
  },
  {
    organization: "Undi95",
    name: "ReMM SLERP L2 (13B)",
    id: "Undi95/ReMM-SLERP-L2-13B",
    contextLength: 4096,
    parameterSize: 13,
  },
  {
    organization: "Undi95",
    name: "Toppy M (7B)",
    id: "Undi95/Toppy-M-7B",
    contextLength: 4096,
    parameterSize: 7,
  },
  {
    organization: "WizardLM",
    name: "WizardLM v1.2 (13B)",
    id: "WizardLM/WizardLM-13B-V1.2",
    contextLength: 4096,
    parameterSize: 13,
  },
  {
    organization: "upstage",
    name: "Upstage SOLAR Instruct v1 (11B)",
    id: "upstage/SOLAR-10.7B-Instruct-v1.0",
    contextLength: 4096,
    parameterSize: 11,
  },   
];
